name: "teaching.notandrewkaye.com"
description: "Course Directory"

url: "http://notandrewkaye.github.io/Teaching/"
baseurl: "/Teaching/"

paginate: 20

#markdown: rdiscount
permalink: /:categories/:title
highlighter: pygments

gems:
- jemoji
- jekyll-sitemap

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/im.html"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
